Create User Page
rafaelalmeidatk/nextjs-forum pull request #84
Opened 2024-09-02 18:12 UTC by anay-208

# Create User Page

## Summary
Me & @Arinji2 have created a user page, which would display the users:
- Recently Marked Answers
- Join Date(A new column is created in users)
- Total Answers
- Modified Ui in posts(WIP)
Screenshot of page:
![User Page](https://github.com/user-attachments/assets/e2191f8c-9e66-4e34-99c7-e9e082fa330b)

## Note
- **Database has been Restructured**:  Added `joinedAt`, and modified index to be sorted.
- **This pull request is a WIP**: Created so the performance for the leaderboard query can be checked
- **New Database Value**: In Sync user, I've added the logic to sync joinedAt, please also note that it'll be empty once the database is migrated.

## Changes Needed
- **Check the performance of leaderboard query**: The performance of leaderboard query needs to be checked, and query needs to be optimised. CC: @rafaelalmeidatk 
- **Changes to UI**: Some additional changes to the UI like of posts page is currently a WIP.

2024-09-02 18:41 UTC, Arinji2 commented
With the latest commit, the Changes to UI are completed.

2024-09-05 06:32 UTC, anay-208 commented
I also checked that if the `joinedAt` column is empty, it'll just not show the value in profile page, until next user sync.

Please also verify it on your end

2024-09-08 21:58 UTC, rafaelalmeidatk requested changes
The page looks great! I left some small suggestions

2024-09-08 21:58 UTC, rafaelalmeidatk commented on apps/web/app/user/[discordID]/page.tsx
> +    .with('rankedUsers', (db) =>
This query works but it is reading every row from the table. I tested the following query and the execution plan seems to be better:
```sql
WITH userAnswers AS
  (SELECT "answersCount"
   FROM users
   WHERE "snowflakeId" = $1
)
SELECT 1 +
  (SELECT COUNT(*)
   FROM users
   WHERE "answersCount" >
       (SELECT "answersCount"
        FROM userAnswers)) AS rank;
```

2024-09-08 21:58 UTC, rafaelalmeidatk commented on apps/web/app/user/[discordID]/page.tsx
> +  // const userData = await getUserData(params.discordID)
Unused code

2024-09-08 21:58 UTC, rafaelalmeidatk commented on packages/db/migrations/6-create-profile-page.ts
> +  await db.schema.dropIndex('users_answersCount_idx').execute()
This is the wrong index name you created on the `up` function

2024-09-10 12:06 UTC, anay-208 commented
@rafaelalmeidatk I also checked the query, and found out if 2 users have the same answerCount, Their rank will be same.

This is completely fine, but the thing is that, it is not how it works in the home page

2024-09-15 18:19 UTC, rafaelalmeidatk commented
> @rafaelalmeidatk I also checked the query, and found out if 2 users have the same answerCount, Their rank will be same.
> 
> This is completely fine, but the thing is that, it is not how it works in the home page

@anay-208 uh yeah that makes sense, we can go back to using `RANK` then and I will monitor the query in the dashboard to make sure it's not using too many resources but it should be fine since we don't update the page very often

2024-09-15 18:28 UTC, anay-208 commented
@rafaelalmeidatk Done

2024-09-15 18:38 UTC, rafaelalmeidatk approved these changes
Thank you, this is awesome 🙏

2024-09-15 18:39 UTC, merged