Add Reply Feature
rafaelalmeidatk/nextjs-forum pull request #92
Opened 2024-12-30 19:02 UTC by Arinji2

This PR adds a reply feature to the forum.
It matches the discord UI and handles most of the edge cases ( i could remember ) at that time. 
Edge Cases + Examples: https://discord.com/channels/752553802359505017/1219272204638748752/1323191809177817118

Referencing Issue: #4 

Mobile Responsiveness is still WIP, @anay-208 mentioned they wanted to try out handling it. Waiting on him to finish with this PR.

2024-12-31 14:42 UTC, anay-208 commented
This PR is still not completed and the following changes are left:
- [ ] If hasReply is true, but message is not found, then display "Original message was deleted"
- [ ] Improve Mobile UI

2025-01-01 05:58 UTC, Arinji2 commented
> This PR is still not completed and the following changes are left:
> 
>     * [x]  If hasReply is true, but message is not found, then display "Original message was deleted"
> 
>     * [x]  Improve Mobile UI

The following have been completed.

2025-01-01 07:53 UTC, anay-208 requested changes

2025-01-01 07:53 UTC, anay-208 commented on apps/web/components/message.tsx
> +        <div className="pointer-events-none flex w-full grow-0 flex-col items-stretch justify-start gap-1 p-2 [&>*]:pointer-events-auto">
```suggestion
        <div className="pointer-events-none flex w-full grow-0 flex-col items-stretch justify-start gap-1 md:gap-0 p-2 [&>*]:pointer-events-auto">
```

I don't think gap is needed for desktop. I was just talking about  adding it for mobile only

2025-01-03 22:33 UTC, rafaelalmeidatk reviewed
Thank you this is great! I left some suggestions

2025-01-03 22:33 UTC, rafaelalmeidatk commented on apps/web/components/message-wrapper.tsx
> +  }, [searchParams, snowflakeId])
This seems to be missing the pathname
```suggestion
  }, [searchParams, snowflakeId, pathname])
```

2025-01-03 22:33 UTC, rafaelalmeidatk commented on apps/web/components/message-wrapper.tsx
> +        window.history.replaceState(null, '', pathname)
We probably don't need this, the id can be kept in the URL

2025-01-03 22:33 UTC, rafaelalmeidatk commented on apps/web/components/message-wrapper.tsx
> +    const searchID = searchParams.get('replyID')
Instead of `replyID` we can make this general to all messages and use `mid`

2025-01-03 22:33 UTC, rafaelalmeidatk commented on apps/web/components/reply.tsx
> +      }}
Wouldn't it be easier to do a simple anchor link to the message element ID?

2025-01-03 22:33 UTC, rafaelalmeidatk commented on apps/web/app/post/[id]/page.tsx
> +                  : undefined
This will simplify the ternary on the JSX, also avoid using "data" as a variable name because most of the time it is too generic to be meaningful
```suggestion
                const replyMessage = hasReply
                  ? allMessages.find(
                      (m) => m.snowflakeId === message.replyToMessageId,
                    )
                  : "deleted"
```

2025-01-04 01:24 UTC, Arinji2 commented on apps/web/components/reply.tsx
> +      }}
Not sure how I can show the highlights for the selected message using anchors.

2025-01-04 06:21 UTC, Arinji2 commented on apps/web/components/message-wrapper.tsx
> +  }, [searchParams, snowflakeId])
Updated to not use pathname

2025-01-04 06:21 UTC, Arinji2 commented on apps/web/components/message-wrapper.tsx
> +        window.history.replaceState(null, '', pathname)
Removed updating the url

2025-01-04 06:24 UTC, Arinji2 commented on apps/web/components/message-wrapper.tsx
> +    const searchID = searchParams.get('replyID')
We use hashes now, so this shouldn't be a problem

2025-01-04 06:25 UTC, Arinji2 commented on apps/web/components/reply.tsx
> +      }}
Fixed, we use hashes and a custom hook now.

2025-01-04 07:33 UTC, anay-208 requested changes

2025-01-04 07:33 UTC, anay-208 commented on apps/web/components/message-wrapper.tsx
> +        } as React.CSSProperties
Why not use `cn` for it? 
Create `cn.ts` in utils, and paste this code::
```ts
import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
```

After that, you can just import cn and conditional check to add the class

2025-01-04 07:37 UTC, anay-208 commented on apps/web/components/message-wrapper.tsx
> +        } as React.CSSProperties
I was just seeing the file changes to see how it works, and noticed this

2025-01-05 16:16 UTC, rafaelalmeidatk commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
We probably don't need this anymore, part of the suggestion of moving to hashes is that we can use `scroll-behavior: smooth;` and get rid of all the JS :raised_hands:

2025-01-05 16:17 UTC, Arinji2 commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
Thing is, that won't center the element.. you need to use js to center it. Or else it's gonna be at the top

2025-01-05 16:19 UTC, anay-208 commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
I don't think it will be a big problem. Even if it's at the top, it should be ok

2025-01-05 16:20 UTC, rafaelalmeidatk commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
I believe we can use [scroll-padding-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top) to avoid this problem

2025-01-05 16:29 UTC, Arinji2 commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
Sure if it dosen't need to be centered, i can just use some absolute scroll padding top value. Will update the PR

2025-01-05 16:51 UTC, Arinji2 commented on apps/web/utils/hooks/useHashFocus.ts
> +    }
Updated the PR, let me know if its good now.

2025-01-05 23:47 UTC, rafaelalmeidatk approved these changes
This looks great, thank you both! 🙏

2025-01-05 23:47 UTC, merged